services:
  linux:
    build:
      context: .
      dockerfile: build/tools/CompileGo.Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: arm64
    image: wastetags:latest
    command: |
      sh -c "cp /wastetags /export/"
    volumes:
      - ./bin/linux:/export

volumes:
  build_output:
    driver: local