// protoc --go_out=. protobuf/schema.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.2
// source: protobuf/schema.proto

package database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chemical struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cas           string                 `protobuf:"bytes,1,opt,name=cas,proto3" json:"cas,omitempty"`
	ChemName      string                 `protobuf:"bytes,2,opt,name=chem_name,proto3" json:"chem_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chemical) Reset() {
	*x = Chemical{}
	mi := &file_protobuf_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chemical) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chemical) ProtoMessage() {}

func (x *Chemical) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chemical.ProtoReflect.Descriptor instead.
func (*Chemical) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Chemical) GetCas() string {
	if x != nil {
		return x.Cas
	}
	return ""
}

func (x *Chemical) GetChemName() string {
	if x != nil {
		return x.ChemName
	}
	return ""
}

type ChemicalList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chemical      []*Chemical            `protobuf:"bytes,1,rep,name=chemical,proto3" json:"chemical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChemicalList) Reset() {
	*x = ChemicalList{}
	mi := &file_protobuf_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChemicalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChemicalList) ProtoMessage() {}

func (x *ChemicalList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChemicalList.ProtoReflect.Descriptor instead.
func (*ChemicalList) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{1}
}

func (x *ChemicalList) GetChemical() []*Chemical {
	if x != nil {
		return x.Chemical
	}
	return nil
}

type Mixture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChemName      string                 `protobuf:"bytes,1,opt,name=chem_name,proto3" json:"chem_name,omitempty"`
	ComponentName string                 `protobuf:"bytes,2,opt,name=component_name,proto3" json:"component_name,omitempty"`
	Cas           string                 `protobuf:"bytes,3,opt,name=cas,proto3" json:"cas,omitempty"`
	Percent       string                 `protobuf:"bytes,4,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mixture) Reset() {
	*x = Mixture{}
	mi := &file_protobuf_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mixture) ProtoMessage() {}

func (x *Mixture) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mixture.ProtoReflect.Descriptor instead.
func (*Mixture) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Mixture) GetChemName() string {
	if x != nil {
		return x.ChemName
	}
	return ""
}

func (x *Mixture) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *Mixture) GetCas() string {
	if x != nil {
		return x.Cas
	}
	return ""
}

func (x *Mixture) GetPercent() string {
	if x != nil {
		return x.Percent
	}
	return ""
}

type MixtureList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mixture       []*Mixture             `protobuf:"bytes,1,rep,name=mixture,proto3" json:"mixture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixtureList) Reset() {
	*x = MixtureList{}
	mi := &file_protobuf_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixtureList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixtureList) ProtoMessage() {}

func (x *MixtureList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixtureList.ProtoReflect.Descriptor instead.
func (*MixtureList) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{3}
}

func (x *MixtureList) GetMixture() []*Mixture {
	if x != nil {
		return x.Mixture
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_protobuf_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type LocationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      []*Location            `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationList) Reset() {
	*x = LocationList{}
	mi := &file_protobuf_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationList) ProtoMessage() {}

func (x *LocationList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationList.ProtoReflect.Descriptor instead.
func (*LocationList) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{5}
}

func (x *LocationList) GetLocation() []*Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Abbreviation  string                 `protobuf:"bytes,2,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_protobuf_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{6}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

type ContainerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     []*Container           `protobuf:"bytes,1,rep,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerList) Reset() {
	*x = ContainerList{}
	mi := &file_protobuf_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerList) ProtoMessage() {}

func (x *ContainerList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerList.ProtoReflect.Descriptor instead.
func (*ContainerList) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerList) GetContainer() []*Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type Unit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Abbreviation  string                 `protobuf:"bytes,2,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unit) Reset() {
	*x = Unit{}
	mi := &file_protobuf_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{8}
}

func (x *Unit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Unit) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

type UnitList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          []*Unit                `protobuf:"bytes,1,rep,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitList) Reset() {
	*x = UnitList{}
	mi := &file_protobuf_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitList) ProtoMessage() {}

func (x *UnitList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitList.ProtoReflect.Descriptor instead.
func (*UnitList) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{9}
}

func (x *UnitList) GetUnit() []*Unit {
	if x != nil {
		return x.Unit
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_protobuf_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{10}
}

func (x *State) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []*State               `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateList) Reset() {
	*x = StateList{}
	mi := &file_protobuf_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateList) ProtoMessage() {}

func (x *StateList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateList.ProtoReflect.Descriptor instead.
func (*StateList) Descriptor() ([]byte, []int) {
	return file_protobuf_schema_proto_rawDescGZIP(), []int{11}
}

func (x *StateList) GetState() []*State {
	if x != nil {
		return x.State
	}
	return nil
}

var File_protobuf_schema_proto protoreflect.FileDescriptor

var file_protobuf_schema_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x22, 0x3a, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x61, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x08, 0x63, 0x68, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x6d, 0x69,
	0x63, 0x61, 0x6c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x6d, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x7b, 0x0a,
	0x07, 0x4d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x6d,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65,
	0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x61, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x0b, 0x4d, 0x69,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x6d,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e,
	0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43,
	0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x62, 0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x62, 0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x62, 0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x62, 0x62, 0x72, 0x65,
	0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x08, 0x55, 0x6e, 0x69, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x6e, 0x69,
	0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x1d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x32, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b,
	0x67, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_schema_proto_rawDescOnce sync.Once
	file_protobuf_schema_proto_rawDescData = file_protobuf_schema_proto_rawDesc
)

func file_protobuf_schema_proto_rawDescGZIP() []byte {
	file_protobuf_schema_proto_rawDescOnce.Do(func() {
		file_protobuf_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_schema_proto_rawDescData)
	})
	return file_protobuf_schema_proto_rawDescData
}

var file_protobuf_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protobuf_schema_proto_goTypes = []any{
	(*Chemical)(nil),      // 0: database.Chemical
	(*ChemicalList)(nil),  // 1: database.ChemicalList
	(*Mixture)(nil),       // 2: database.Mixture
	(*MixtureList)(nil),   // 3: database.MixtureList
	(*Location)(nil),      // 4: database.Location
	(*LocationList)(nil),  // 5: database.LocationList
	(*Container)(nil),     // 6: database.Container
	(*ContainerList)(nil), // 7: database.ContainerList
	(*Unit)(nil),          // 8: database.Unit
	(*UnitList)(nil),      // 9: database.UnitList
	(*State)(nil),         // 10: database.State
	(*StateList)(nil),     // 11: database.StateList
}
var file_protobuf_schema_proto_depIdxs = []int32{
	0,  // 0: database.ChemicalList.chemical:type_name -> database.Chemical
	2,  // 1: database.MixtureList.mixture:type_name -> database.Mixture
	4,  // 2: database.LocationList.location:type_name -> database.Location
	6,  // 3: database.ContainerList.container:type_name -> database.Container
	8,  // 4: database.UnitList.unit:type_name -> database.Unit
	10, // 5: database.StateList.state:type_name -> database.State
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_schema_proto_init() }
func file_protobuf_schema_proto_init() {
	if File_protobuf_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_schema_proto_goTypes,
		DependencyIndexes: file_protobuf_schema_proto_depIdxs,
		MessageInfos:      file_protobuf_schema_proto_msgTypes,
	}.Build()
	File_protobuf_schema_proto = out.File
	file_protobuf_schema_proto_rawDesc = nil
	file_protobuf_schema_proto_goTypes = nil
	file_protobuf_schema_proto_depIdxs = nil
}
